[addresses]
  balanced = '0xf431e609f95848ceb448563bce855cc7075713fb25c4b5996d9495800615eef6'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.balanced_dollar]
    local = 'balanced_dollar'

  [dependencies.xcall]
    git = 'https://github.com/icon-project/xcall-multi.git'
    rev = 'sui-xcall-testnet-deploy'
    subdir = 'contracts/sui/xcall'

[package]
  edition = '2024.beta'
  name = 'balanced'
  published-at = '0xf431e609f95848ceb448563bce855cc7075713fb25c4b5996d9495800615eef6'
  version = '0.0.1'
