[addresses]
  balanced = '0x3b2b85d607328c0fa69c5073738ff469f8502d6de9036ddf162d11eadaf4f75d'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.balanced_dollar]
    local = 'balanced_dollar'

  [dependencies.xcall]
    git = 'https://github.com/icon-project/xcall-multi.git'
    rev = 'feat/sui-xcall-testnet'
    subdir = 'contracts/sui/xcall'

[package]
  edition = '2024.beta'
  name = 'balanced'
  published-at = '0x3b2b85d607328c0fa69c5073738ff469f8502d6de9036ddf162d11eadaf4f75d'
  version = '0.0.1'
