[addresses]
  balanced_crosschain = '0x3b9bd13f9f14945b978a319223cf2af1d8302ff531df0df7a9349af848fa6455'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.balanced]
    local = '../balanced'

  [dependencies.balanced_dollar]
    local = '../balanced_tokens/balanced_dollar'

  [dependencies.balanced_token]
    local = '../balanced_tokens/balanced_token'

  [dependencies.sicx]
    local = '../balanced_tokens/sicx'

  [dependencies.xcall]
    git = 'https://github.com/icon-project/xcall-multi.git'
    rev = 'sui-xcall-testnet-deploy'
    subdir = 'contracts/sui/xcall'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.beta'
  name = 'balanced_crosschain'
  published-at = '0x3b9bd13f9f14945b978a319223cf2af1d8302ff531df0df7a9349af848fa6455'
