[addresses]
  balanced = '0x2bda1780dc59243386d205f1855cde689dbbb87003d71a2518832638589d48cf'
  balanced_crosschain = '0x0'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/mainnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

  [dependencies.balanced]
    local = '../balanced'

  [dependencies.balanced_dollar]
    local = '../balanced_tokens/balanced_dollar'

  [dependencies.balanced_token]
    local = '../balanced_tokens/balanced_token'

  [dependencies.sicx]
    local = '../balanced_tokens/sicx'

  [dependencies.xcall]
    git = 'https://github.com/icon-project/xcall-multi.git'
    rev = 'sui-xcall-mainnet-deploy'
    subdir = 'contracts/sui/xcall'

[dev-addresses]

[dev-dependencies]

[package]
  edition = '2024.beta'
  name = 'balanced_crosschain'
  published-at = '0x0420fdd0afe2f06f2ecac4395503565dcb6abaf4b5310298d4abe5f2667911ad'
