[addresses]
  balanced_dollar = '0xe5da7d5101f68866d4aa447829bed80e477f5cbbdca41fd9d7e428e85b0ad297'

[dependencies]
  [dependencies.Sui]
    git = 'https://github.com/MystenLabs/sui.git'
    rev = 'framework/testnet'
    subdir = 'crates/sui-framework/packages/sui-framework'

[package]
  edition = '2024.beta'
  name = 'balanced_dollar'
  published-at = '0xe5da7d5101f68866d4aa447829bed80e477f5cbbdca41fd9d7e428e85b0ad297'
  version = '0.0.1'
